### ISSUE TITLE
How to specify an order for the Classes?

### ISSUE THREAD

**Issue by gaelcolas** [PoshCode/ModuleBuilder#18]
As you know Classes sometimes need to be imported or merged in a specific order.

I haven't found an elegant way of importing them in a specific order without prepending a number in the file name (which I'm not a fan of either).
 
e.g.:
```
1.ClassA.ps1
2.ClassC.ps1
3.ClassB.ps1
```
I tend to prefer specifying the order in a PSD1 and/or sorting the files within the Classes folder for merging them in the PSM1, but that's a bit over-engineered:

```PowerShell
$order = {(Import-PowerShellDataFile -EA 0 .\Classes\classes.psd1).order.indexOf($_.BaseName)}
Get-ChildItem $FilePath -Filter *.ps1 -Recurse | Sort-Object $Order | Merge-ToModule $ModuleInfo
```

Happy to go with file names (less code), if that's your intent.

**Comment by Jaykul** [comment]
We specifically talked about this during design.

The **only** _correct_ answer is for **PowerShell** to fix this so the order doesn't matter. 

Anything else is a workaround. 

In my opinion, the simplest workarounds are the best: number your files to force the order. It's not only simple, it's easy and obvious (people who look at the code can see you deliberately ordered the files). In the worst case, we need to add an explicit `Sort-Object Name` to preserve the order in a cross-platform way (I'm not totally sure Get-ChildItem is inherently ordered), but this has been working for me.

The only other ordering that we follow is that the SourceDirectories are processed in order. If you really want to, you can use and abuse that to get anything you need (please don't).  In fact, at design time I gave in to adding the "enum" folder (which I personally think is a **bad** idea, and won't use) because so many of the folks who were present were convinced that enums are different, and this would be enough for them to handle their dependencies.

I would be happy to consider automatically determining the order at compile time if anyone wants to have a go at that, but right now I don't really think it's worth the effort (except that I'd love for that to be built in to PowerShell).

**Comment by gaelcolas** [comment]
Good for me.

**Comment by Jaykul** [comment]
What do you think of adding a sort-of pre-compiler directive option, like ... if you put a line at the top of the file:
```
#using class OtherClass, EnumFour
```

then we could just read the **very first line** and sort by that?

**Comment by Jaykul** [comment]
Is this actually a problem?

I just tried putting this in a `Test.psm1` file:

```PowerShell
class Computer {
    [string]$Name
    [Person]$Owner
    [string]ToString() { return $this.Name }
}

class Person {
    [string]$Name
    [Computer]$Computer
    [string]ToString() { return $this.Name }
}

function New-User {
    [CmdletBinding()]
    param([Parameter(Mandatory)]$UserName, $ComputerName)
    $P = [Person]@{
        Name = $UserName
    }
    $C = [Computer]@{
        Name = $ComputerName
        Owner = $P
    }
    $P.Computer = $C

    $P
}
```

That seems to work even in PowerShell 5 ...

**Comment by gaelcolas** [comment]
You're right, it is not a problem in a compiled PSM1. 
It matters only when dot sourcing, which is what I use to do for reasons similar to #35. 
I was importing the classes in the sessions similar to scripts to process (yeah, really hacky) for troubleshooting.
