### ISSUE TITLE
[Documentation] Build-Module parameter -Target

### ISSUE THREAD

**Issue by LaurentDardenne** [PoshCode/ModuleBuilder#39]
Its possible values are not explained :

> [ValidateSet("Clean", "Build", "CleanBuild")]

Regarding its behavior, should the value Clean delete the versioned directory?
![image](https://user-images.githubusercontent.com/4894452/49588548-489d0d80-f967-11e8-84b2-321b88ff261c.png)

build.pds1:
```Powershell
@{
    Path = "MyModule.psd1"
    OutputDirectory = "C:\temp\Delivery\MyModule"
    VersionedOutputDirectory = $true
    CopyDirectories=@('.\Demos','.\fr-FR','.\TypeData')
}
```

**Comment by Jaykul** [comment]
I'm a little concerned about cleaning 😉 

During testing at one point, I put `OutputDirectory = "..\..\"` thinking of it as relative to the build.psd1 and found to my chagrin that it was not ... I've fixed that now, but only after recovering a lot more files from my backups than I have ever needed to before...

But yes, in order to be a real "clean", -Clean should delete the version number folder. It may be, however, that we're recreating the folder _after_ clean, even when we're not going to build. That would be a bug.

**Comment by Jaykul** [comment]
The way this is currently implemented, it deletes only the CONTENTS of the folder, because it assumes it's going to re-build it.
I think we should probably implement it such that if we're NOT building, we delete the folder too...

Should I not be worried people will screw this up? I mean, even playing with it just now, I blew away the whole module source because it was using a build.psd1 with:

```
OutputDirectory = ".."
VersionedOutputDirectory = $true
```
And I turned off the `VersionedOutputDirectory` and also specified `Clean` ...
