### ISSUE TITLE
Installation of dependencies does not work on old PowershellGet

### ISSUE THREAD

**Issue by lipkau** [PoshCode/ModuleBuilder#41]
https://github.com/PoshCode/ModuleBuilder/blob/0ca3cc66d89fe0acc4ba644b53d3aba8e2fa7eac/bootstrap.ps1#L12

In PowershellGet v1.0.0.1 :

> ```
> Install-Module : Cannot validate argument on parameter 'MaximumVersion'. The argument is null. > Provide a valid value for the argument, and then try running the command again.
> At C:\Users\olive\Projects\ConfluencePS\Tools\BuildTools.psm1:59 char:28
> + ... edModules | Install-Module -Scope $Scope -Repository PSGallery -SkipP ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (@{ ModuleName =...ion = '5.4.2' }:ModuleSpecification) [Install-> Module], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationError,Install-Module
>```

**Comment by kilasuit** [comment]
PowerShellGet v1.0.0.1 was a VERY Broken version

For starters 

There was many different versions of this version - all updated inbox within windows as part of Windows updates in the Windows 10 insider builds
Because of that I'd seriously reccommend updating to v 1.6.0 or later on any box that has it and is being used as a build box or even a development / production workload

Also it's hideously out of date and lots of issues will occur just staying with that version - I personally would suggest that v1.0.0.1 is unsupported and technically **unsupportable** because of the changes that occurred between different windows 10 builds

**Comment by lipkau** [comment]
I'd be 100% onboard... if this was distributed via windows updates/WSUS.
All my machines had the 1.0.0.1 version on it. and at work, less than 30% of my users have admin permissions to update the module.

**Comment by kilasuit** [comment]
You don't need admin permissions to update the module - can always update it at the Current User Scope not all Users Scope

`I'd be 100% onboard... if this was distributed via windows updates/WSUS.` - technically that is **exactly** why that version of PowerShellGet is broken. There was a ridiculously long thread about this in the MVP Distribution list at the time. I personally advocated for PowerShellGet to be Open Sourced and decoupled from PowerShell Core (amongst others) in this issue https://github.com/PowerShell/PowerShell/issues/1979

**Comment by SimonWahlin** [comment]
We could add:
`#Requires -Modules @{ModuleName='PowerShellGet';ModuleVersion='1.6.0'}`
to the top of bootstrap.ps1 just to make it more clear what we expect?

**Comment by Jaykul** [comment]
Or we could have it check and upgrade you 🙊

**Comment by lipkau** [comment]
Offer to is fine. Force it? I wouldn't like it.
I agree with simon
