### ISSUE TITLE
Adding option for parsing public Functions and Aliases

### ISSUE THREAD

**Issue by SimonWahlin** [PoshCode/ModuleBuilder#50]
First off, I realize that this might be a highly opinionated subject and don't mind to be told that I'm wrong.

Today, Build-Module reads the BaseName of files matching $PublicFilter to populate FunctionsToExport, which works well enough unless you misspell a file or want to have more than one function per file. My main problem is that this method won't export any aliases for commands, meaning that I will have to either set AliasesToExport to '*' which is bad for performance or parse my aliases in a post-build task.

I would like to add an option to use AST to get all functions and aliases from all files matching $PublicFilter. This option could be enabled by a swich parameter $UseAST. I am aware that this will have an impact on build performance. In my testing on a small module with ~20 public functions, this change takes the build time from ~0.35seconds to ~0.7 seconds, an impact I'm gladly willing to endure to get Aliases parsed for me.

Would a PR for this be of interest?

**Comment by Jaykul** [comment]
Automatically exporting `[Alias(...)]` attributes from public functions makes sense to me, and I can live with the cost of parsing the output module to read those.  It's probably not something we should _force_ on authors, since they should be able to define aliases for their own use, and even export aliases that are defined in other ways...

However, I'm concerned that implicit in the idea that you would _deliberately allow_ source file names to not match the functions you export from them, is the fact that you would also allowing the definition of multiple functions per file ... which is going to get messy.

And in any case, I was trying to avoid reading the source files multiple times...

Currently we only read files _within_ [SetModuleContent](https://github.com/PoshCode/ModuleBuilder/blob/master/Source/Private/SetModuleContent.ps1) which is a proxy command for Set-Content, and is being called _only once_ with _all_ the source files at once, not just the public ones (this way we only open the output file once, write all the content to it, and then close it).

My proposal for implementing what you're asking for would be:

1. A switch parameter $AutomaticAliasExports (or just $AliasExports)
2. AST parse the whole module and FindAll `FunctionDefinitionAst` statements with names that are already in our `$PublicFunctions` list ...
3. Extract their `Body.ParamBlock.Attributes.Where{ $_.TypeName.Name -eq "Alias" }.PositionalArguments.Value` or something

Thoughts? Counter-arguments?

**Comment by AspenForester** [comment]
I just had a co-worker ask me about aliases not getting exported this morning.

**Comment by jmiller76** [comment]
Realizing that this is a just a quick hack I added this below $output = Build-Module .... and it is working for now.  Tweaks are needed based on how you add spaces and switch between ' and ", but until a permanent change is in place, this should help. 

$alias = Get-ChildItem (Join-Path $here '\source\Public\') '*.ps1' -Recurse | Select-String @'
(?<=\[alias\(')[^']*(?='\)\])
'@ | ForEach-Object { $_.Matches.Value }
Update-ModuleManifest $output.Path  -AliasesToExport $Alias

**Comment by gaelcolas** [comment]
@Jaykul could you release latest, pretty please :)
