### ISSUE TITLE
Version 1.5.2 cannot read the manifest file

### ISSUE THREAD

**Issue by bravo-kernel** [PoshCode/ModuleBuilder#87]
After upgrading ModuleBuilder to 1.5.2 my build-phase is broken. It looks like the manifest file cannot be _found_.  After pinning 1.0.0 the problem is gone.

Since there are no messages/warnings in the log, any pointers on what could be amiss here?

## Info

- **[failing 1.5.2 build log](https://dev.azure.com/alt3bv/Docusaurus.Powershell/_build/results?buildId=538&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=00170b8f-1061-5420-820e-1eb883d5ca57)**
- [successful 1.0.0 build log](https://dev.azure.com/alt3bv/Docusaurus.Powershell/_build/results?buildId=545&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=00170b8f-1061-5420-820e-1eb883d5ca57)
- my [manifest file](https://github.com/alt3/Docusaurus.Powershell/blob/master/Source/Alt3.Docusaurus.Powershell.psd1) is and always has been UTF-8 with BOM
- building on PSVersion 5.1.17763.771, PSEdition Desktop

**Comment by mattmcnabb** [comment]
@bravo-kernel I just ran into the same issue and at least in my case, the problem is with the `-Path` parameter of `Build-Module`. I found that this is now called `-ModuleManifest`. If you're calling `-Path` try changing to `-ModuleManifest` to see if that fixes it.

If that works I think there are some documentation problems that need to be addressed.

**Comment by bravo-kernel** [comment]
@mattmcnabb thanks for responding, I just gave `ModuleManifest` a try but unfortunately with the same result. Let's hope someone can make some sense out of this.

![image](https://user-images.githubusercontent.com/230500/71687058-30333880-2d9d-11ea-9a10-cb1f5005da40.png)

**Comment by Jaykul** [comment]
You misunderstood. If you put `ModuleManifest` in your `Build.psd1` (instead of `Path`), then it works.

This is clearly a bug related to #49 and the code I wrote to parse build.psd1 and handle aliases. That parameter, in particular, was a real pain because it's always _already_ set, but _almost_ always needs to be overwritten anyway.

**Comment by bravo-kernel** [comment]
I can confirm that I indeed misunderstood. After updating `Source/build.psd1` to use `ModuleManifest` instead of `Path`... ci is now happily building again.

**Comment by bravo-kernel** [comment]
@mattmcnabb sorry about that, you already gave me the solution ;)
